import Head from 'next/head';
// components
import Main from '../components/Main.jsx';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Enhance Your Reality | Qü</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Main />
      </main>
    </div>
  )
}
