import Head from 'next/head';
// components
import Navbar from '../components/global/Navbar';
import Main from '../components/home/Main';
import Services from '../components/home/Services';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Enhance Your Reality | Qü</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        <Main />
        <Services />
      </main>
    </div>
  )
}
